[[plugins]]
repo = 'vim-denops/denops.vim'
on_source = ['vim-gin', 'mr.vim', 'ddu.vim']

# [[plugins]]
# repo = 'lambdalisue/kensaku.vim'
# depends = ['kensaku.vim']
# hook_source = 'cnoremap <CR> <Plug>(kensaku-search-replace)<CR>'

# [[plugins]]
# repo = 'lambdalisue/vim-kensaku-search'
# depends = ['denops.vim']

[[plugins]]
repo = 'lambdalisue/vim-gin'
depends = ['denops.vim']

[[plugins]]
repo = 'Shougo/pum.vim'
on_source = 'ddc.vim'
hook_post_source = '''
  inoremap <expr> <Tab>   pum#visible() ? "<Cmd>call pum#map#insert_relative(+1)<CR>" : "<Tab>"
  inoremap <expr> <S-Tab> pum#visible() ? "<Cmd>call pum#map#insert_relative(-1)<CR>" : "<S-Tab>"
  inoremap <expr> <C-n>   pum#visible() ? "<Cmd>call pum#map#insert_relative(+1)<CR>" : "<C-n>"
  inoremap <expr> <C-p>   pum#visible() ? "<Cmd>call pum#map#insert_relative(-1)<CR>" : "<C-p>"
  inoremap <expr> <CR>    pum#visible() ? "<Cmd>call pum#map#confirm()<CR>" : "<CR>"
  inoremap <expr> <C-e>   pum#visible() ? "<Cmd>call pum#map#cancel()<CR>" : "<C-e>"
'''

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
on_event = 'InsertEnter'
hook_source = 'call config#ddc#init()'

[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['pum.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-source-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-filter-converter_remove_overlap'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/ddc-buffer'
on_source = 'ddc.vim'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = ['denops.vim']
on_source = 'ddc.vim'
hook_post_source = '''
  call skkeleton#config({ 
  \   'userDictionary': expand('~/.skk/skk-jisyo.utf8'),
  \   'globalDictionaries': [
  \     ['~/.skk/SKK-JISYO.L', 'euc-jp'],
  \     ['~/.skk/SKK-JISYO.geo', 'euc-jp'],
  \     ['~/.skk/SKK-JISYO.jinmei', 'euc-jp'],
  \     ['~/.skk/SKK-JISYO.propernoun', 'euc-jp'],
  \     ['~/.skk/SKK-JISYO.station', 'euc-jp'],
  \   ] 
  \ })
  inoremap <C-j> <Plug>(skkeleton-enable)
  cnoremap <C-j> <Plug>(skkeleton-enable)
'''

[[plugins]]
repo = 'github/copilot.vim'
on_event = 'InsertEnter'
