# [[plugins]]
# repo = 'iamcco/markdown-preview.nvim'
# on_ft = ['markdown']
# build = 'sh -c "cd app && yarn install"'

[[plugins]]
repo = 'kat0h/bufpreview.vim'
on_ft = ['markdown']
build = 'deno task prepare'
